# Generated by Django 3.0.5 on 2020-05-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_auto_20200526_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
